"""Unit tests for the VALUE_SEARCH algorithm (UC10 — column-value membership search).

Uses a tiny in-Python SQL emulator (``FakeSqlConnector``) that parses the
queries the algorithm actually generates — the DISTINCT source-value fetch,
the EXACT ``IN (...) GROUP BY`` scan, the PATTERN ``SUM(CASE WHEN ... LIKE``
scan, and the evidence ``SELECT * ... LIMIT`` — and answers them from an
in-memory row list.  This exercises the real SQL-building logic in
``value_search.py`` rather than bypassing it.
"""

import re
from typing import Any, Dict, List, Optional

import pandas as pd
import pytest

from dimer.core.algorithms.value_search import ValueSearchAlgorithm
from dimer.core.models import (
    ColumnMetadata,
    ConnectionConfig,
    QueryResult,
    SearchMode,
    TableMetadata,
)
from dimer.core.search import ValueSearch

pytestmark = pytest.mark.unit

_DISTINCT_RE = re.compile(
    r'^SELECT DISTINCT CAST\("(?P<col>\w+)" AS TEXT\) AS _dimer_v FROM \S+ '
    r'WHERE "(?P=col)" IS NOT NULL LIMIT (?P<limit>\d+)$'
)
_EXACT_RE = re.compile(
    r'^SELECT CAST\("(?P<col>\w+)" AS TEXT\) AS _dimer_v, COUNT\(\*\) AS _dimer_c '
    r'FROM \S+ WHERE CAST\("(?P=col)" AS TEXT\) IN \((?P<inlist>.*)\) GROUP BY 1$'
)
_PATTERN_EXPR_RE = re.compile(
    r"SUM\(CASE WHEN CAST\(\"(?P<col>\w+)\" AS TEXT\) LIKE "
    r"'(?P<pattern>(?:[^']|'')*)' THEN 1 ELSE 0 END\) AS (?P<alias>m\d+)"
)
_EVIDENCE_RE = re.compile(
    r'^SELECT \* FROM \S+ WHERE CAST\("(?P<col>\w+)" AS TEXT\) '
    r"(?P<op>=|LIKE) '(?P<val>(?:[^']|'')*)' LIMIT (?P<limit>\d+)$"
)
_SQL_STR_RE = re.compile(r"'((?:[^']|'')*)'")


def _unescape(s: str) -> str:
    return s.replace("''", "'")


class FakeSqlConnector:
    """Emulates just enough SQL to satisfy ValueSearchAlgorithm's queries."""

    DIALECTS = {
        "hash": "MD5({COL}::text)",
        "concatenation": "||",
        "cast_to_text": "CAST({COL} AS TEXT)",
    }

    def __init__(self, rows: List[Dict[str, Any]], metadata: TableMetadata) -> None:
        self.rows = rows
        self._metadata = metadata
        self.connection_config = ConnectionConfig(host="host", database="db")
        self.queries: List[str] = []

    def get_table_metadata(self, table_name, schema_name=None) -> TableMetadata:
        return self._metadata

    @staticmethod
    def _text(v: Any) -> Optional[str]:
        return None if v is None else str(v)

    @staticmethod
    def _like(text: str, pattern: str) -> bool:
        # Only '%...%' containment patterns are generated by the algorithm
        assert pattern.startswith("%") and pattern.endswith("%"), pattern
        return pattern[1:-1] in text

    def execute_query(self, query: str, params=None) -> QueryResult:
        self.queries.append(query)
        out_rows: List[Dict[str, Any]]

        m = _DISTINCT_RE.match(query)
        if m:
            col, limit = m.group("col"), int(m.group("limit"))
            seen: List[str] = []
            for r in self.rows:
                t = self._text(r.get(col))
                if t is not None and t not in seen:
                    seen.append(t)
            out_rows = [{"_dimer_v": v} for v in seen[:limit]]
            return self._result(out_rows, query)

        m = _EXACT_RE.match(query)
        if m:
            col = m.group("col")
            wanted = {_unescape(s) for s in _SQL_STR_RE.findall(m.group("inlist"))}
            counts: Dict[str, int] = {}
            for r in self.rows:
                t = self._text(r.get(col))
                if t is not None and t in wanted:
                    counts[t] = counts.get(t, 0) + 1
            out_rows = [{"_dimer_v": v, "_dimer_c": c} for v, c in counts.items()]
            return self._result(out_rows, query)

        exprs = _PATTERN_EXPR_RE.findall(query)
        if exprs and query.startswith("SELECT SUM(CASE"):
            out: Dict[str, int] = {}
            for col, pattern, alias in exprs:
                pat = _unescape(pattern)
                out[alias] = sum(
                    1 for r in self.rows
                    if (t := self._text(r.get(col))) is not None and self._like(t, pat)
                )
            return self._result([out], query)

        m = _EVIDENCE_RE.match(query)
        if m:
            col, op, val, limit = (
                m.group("col"), m.group("op"), _unescape(m.group("val")), int(m.group("limit"))
            )
            if op == "=":
                hit = lambda t: t == val
            else:
                hit = lambda t: self._like(t, val)
            out_rows = [
                r for r in self.rows
                if (t := self._text(r.get(col))) is not None and hit(t)
            ][:limit]
            return self._result(out_rows, query)

        raise AssertionError(f"Unparseable query from algorithm: {query!r}")

    @staticmethod
    def _result(rows: List[Dict[str, Any]], query: str) -> QueryResult:
        return QueryResult(
            data=pd.DataFrame(rows), execution_time=0.0, rows_affected=len(rows), query=query
        )


def _col(name, data_type="string"):
    return ColumnMetadata(name=name, data_type=data_type, nullable=True)


SOURCE_META = TableMetadata(columns=[_col("customer_id")])
SOURCE_ROWS = [
    {"customer_id": "C1"},
    {"customer_id": "C2"},
    {"customer_id": "C3"},
    {"customer_id": None},
    {"customer_id": "C1"},  # duplicate — DISTINCT collapses it
]

TARGET_META = TableMetadata(columns=[_col("id", "int64"), _col("customer_ref"), _col("note")])
TARGET_ROWS = [
    {"id": 1, "customer_ref": "C1", "note": "order for C1"},
    {"id": 2, "customer_ref": "C1", "note": "repeat"},
    {"id": 3, "customer_ref": "C2", "note": "order C2 rush"},
    {"id": 4, "customer_ref": "X9", "note": None},
]


def _run(
    source_rows=SOURCE_ROWS, source_meta=SOURCE_META,
    target_rows=TARGET_ROWS, target_meta=TARGET_META,
    mode=SearchMode.EXACT, source_overrides=None, target_overrides=None,
):
    source = FakeSqlConnector(source_rows, source_meta)
    target = FakeSqlConnector(target_rows, target_meta)
    run = ValueSearchAlgorithm(
        source, target,
        {"fq_table_name": "public.customers", "source_column": "customer_id",
         **(source_overrides or {})},
        {"fq_table_name": "public.orders", **(target_overrides or {})},
        mode=mode,
    ).run()
    return run, source, target


class TestExactSearch:
    def test_counts_and_summary(self):
        run, _, _ = _run()
        assert run.error is None
        assert run.mode == SearchMode.EXACT
        assert run.values_searched == 3          # C1, C2, C3 (NULL and dup dropped)
        assert run.values_found == 2             # C1, C2
        assert run.values_not_found == ["C3"]

        by_key = {(m.value, m.column): m.occurrence_count for m in run.matches}
        assert by_key == {("C1", "customer_ref"): 2, ("C2", "customer_ref"): 1}

    def test_column_stats_rank_matching_column_first(self):
        run, _, _ = _run()
        assert run.columns_searched == ["id", "customer_ref", "note"]
        top = run.column_stats[0]
        assert top.column == "customer_ref"
        assert top.values_matched == 2
        assert top.total_occurrences == 3
        assert top.hit_rate == pytest.approx(2 / 3)
        assert all(s.values_matched == 0 for s in run.column_stats[1:])

    def test_matches_sorted_by_occurrence_desc(self):
        run, _, _ = _run()
        assert [m.occurrence_count for m in run.matches] == [2, 1]

    def test_evidence_rows_attached_to_top_matches(self):
        run, _, _ = _run()
        top = run.matches[0]
        assert top.value == "C1"
        assert len(top.evidence_rows) == 2
        assert {r["id"] for r in top.evidence_rows} == {1, 2}

    def test_cross_type_match_int_column(self):
        # Source values '1'/'2' (text-cast) match the int64 id column via CAST
        source_rows = [{"customer_id": 1}, {"customer_id": 2}, {"customer_id": 99}]
        run, _, _ = _run(source_rows=source_rows)
        by_key = {(m.value, m.column): m.occurrence_count for m in run.matches}
        assert by_key == {("1", "id"): 1, ("2", "id"): 1}
        assert run.values_not_found == ["99"]

    def test_target_columns_filter(self):
        run, _, target = _run(target_overrides={"target_columns": ["note"]})
        assert run.columns_searched == ["note"]
        assert run.values_found == 0  # exact 'C1' != 'order for C1'
        assert all('"customer_ref"' not in q for q in target.queries)

    def test_chunking_splits_in_lists(self):
        source_rows = [{"customer_id": f"V{i}"} for i in range(1200)]
        run, _, target = _run(
            source_rows=source_rows,
            source_overrides={"max_values": 1200},
            target_overrides={"target_columns": ["customer_ref"]},
        )
        assert run.values_searched == 1200
        exact_queries = [q for q in target.queries if "GROUP BY 1" in q]
        assert len(exact_queries) == 3  # 1200 values / 500 per chunk


class TestPatternSearch:
    def test_substring_containment(self):
        run, _, _ = _run(mode=SearchMode.PATTERN)
        by_key = {(m.value, m.column): m.occurrence_count for m in run.matches}
        # 'C1' appears exactly in customer_ref (×2) and inside two notes;
        # 'C2' exactly in customer_ref and inside one note
        assert by_key[("C1", "customer_ref")] == 2
        assert by_key[("C1", "note")] == 1   # "order for C1" only ("repeat" has no C1)
        assert by_key[("C2", "note")] == 1   # "order C2 rush"
        assert run.values_not_found == ["C3"]

    def test_match_mode_recorded_on_matches(self):
        run, _, _ = _run(mode=SearchMode.PATTERN)
        assert all(m.match_mode == SearchMode.PATTERN for m in run.matches)


class TestGuardsAndLimits:
    def test_max_values_truncation_flagged(self):
        run, _, _ = _run(source_overrides={"max_values": 2})
        assert run.values_searched == 2
        assert run.metadata["source_values_truncated"] is True

    def test_unsearchable_column_skipped(self):
        meta = TableMetadata(columns=[_col("customer_ref"), _col("payload", "json")])
        run, _, _ = _run(target_meta=meta, target_rows=[{"customer_ref": "C1"}])
        assert run.columns_searched == ["customer_ref"]
        assert run.metadata["columns_skipped"] == ["payload"]

    def test_empty_source_values_is_error(self):
        run, _, _ = _run(source_rows=[{"customer_id": None}])
        assert run.error is not None
        assert "No non-null values" in run.error

    def test_non_sql_connector_is_error(self):
        source = FakeSqlConnector(SOURCE_ROWS, SOURCE_META)
        source.SUPPORTS_SQL = False
        run = ValueSearchAlgorithm(
            source, FakeSqlConnector(TARGET_ROWS, TARGET_META),
            {"fq_table_name": "public.customers", "source_column": "customer_id"},
            {"fq_table_name": "public.orders"},
        ).run()
        assert run.error is not None
        assert "SQL" in run.error

    def test_missing_source_column_raises(self):
        with pytest.raises(ValueError, match="source_column"):
            ValueSearchAlgorithm(
                FakeSqlConnector(SOURCE_ROWS, SOURCE_META),
                FakeSqlConnector(TARGET_ROWS, TARGET_META),
                {"fq_table_name": "public.customers"},
                {"fq_table_name": "public.orders"},
            )


class TestFacade:
    def test_value_search_facade_delegates(self):
        run = ValueSearch(
            FakeSqlConnector(SOURCE_ROWS, SOURCE_META),
            FakeSqlConnector(TARGET_ROWS, TARGET_META),
            {"fq_table_name": "public.customers", "source_column": "customer_id"},
            {"fq_table_name": "public.orders"},
            mode=SearchMode.EXACT,
        ).search()
        assert run.error is None
        assert run.values_found == 2
